version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env/development/database
      - .env/development/web
    depends_on:
      - webpack
    volumes:
      - .:/usr/src/app:cached
  
  webpack:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: